# .streamlit/secrets.toml

# Replace <password> with your actual MongoDB Atlas password
MONGO_URI = "mongodb+srv://jason:bsidata@bsicluster.uifuc9m.mongodb.net/?appName=BSICluster"

# You can also store your Admin password here for the manual trigger
ADMIN_PASS = "WE7AJNoQ456^%$"